/*
 * Copyright 2023 LINE Corporation
 *
 * LINE Corporation licenses this file to you under the Apache License,
 * version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.linecorp.bot.messaging.model;

import java.time.Instant;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

import com.fasterxml.jackson.annotation.JsonEnumDefaultValue;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

import com.linecorp.bot.messaging.model.Action;


/**
 * DatetimePickerAction
 * @see <a href="https://developers.line.biz/en/reference/messaging-api/#datetime-picker-action"> Documentation</a>
 */
@JsonTypeName("datetimepicker")

@JsonInclude(Include.NON_NULL)
@javax.annotation.Generated(value = "com.linecorp.bot.codegen.LineJavaCodegenGenerator")
public record DatetimePickerAction (
/**
    * Label for the action.
    */
    
    @Nullable
    @JsonProperty("label")
    String label,
/**
    * Get data
    */
    
    @Nullable
    @JsonProperty("data")
    String data,
/**
    * Get mode
    */
    
    @Nullable
    @JsonProperty("mode")
    Mode mode,
/**
    * Get initial
    */
    
    @Nullable
    @JsonProperty("initial")
    String initial,
/**
    * Get max
    */
    
    @Nullable
    @JsonProperty("max")
    String max,
/**
    * Get min
    */
    
    @Nullable
    @JsonProperty("min")
    String min

) implements Action {
/**
     * Gets or Sets mode
     */
    public enum Mode {
@JsonProperty("date")
      DATE,
    @JsonProperty("time")
      TIME,
    @JsonProperty("datetime")
      DATETIME,
    

      @JsonEnumDefaultValue
      UNDEFINED;
    }


}
