/*
 * Copyright 2023 LINE Corporation
 *
 * LINE Corporation licenses this file to you under the Apache License,
 * version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.linecorp.bot.messaging.model;

import java.time.Instant;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

import com.fasterxml.jackson.annotation.JsonEnumDefaultValue;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

import com.linecorp.bot.messaging.model.Action;
import com.linecorp.bot.messaging.model.FlexComponent;


/**
 * FlexButton
 */
@JsonTypeName("button")

@JsonInclude(Include.NON_NULL)
@javax.annotation.Generated(value = "com.linecorp.bot.codegen.LineJavaCodegenGenerator")
public record FlexButton (
/**
    * Get flex
    */
    
    @Nullable
    @JsonProperty("flex")
    Integer flex,
/**
    * Get color
    */
    
    @Nullable
    @JsonProperty("color")
    String color,
/**
    * Get style
    */
    
    @Nullable
    @JsonProperty("style")
    Style style,
/**
    * Get action
    */
    
    @Nonnull
    @JsonProperty("action")
    Action action,
/**
    * Get gravity
    */
    
    @Nullable
    @JsonProperty("gravity")
    Gravity gravity,
/**
    * Get margin
    */
    
    @Nullable
    @JsonProperty("margin")
    String margin,
/**
    * Get position
    */
    
    @Nullable
    @JsonProperty("position")
    Position position,
/**
    * Get offsetTop
    */
    
    @Nullable
    @JsonProperty("offsetTop")
    String offsetTop,
/**
    * Get offsetBottom
    */
    
    @Nullable
    @JsonProperty("offsetBottom")
    String offsetBottom,
/**
    * Get offsetStart
    */
    
    @Nullable
    @JsonProperty("offsetStart")
    String offsetStart,
/**
    * Get offsetEnd
    */
    
    @Nullable
    @JsonProperty("offsetEnd")
    String offsetEnd,
/**
    * Get height
    */
    
    @Nullable
    @JsonProperty("height")
    Height height,
/**
    * Get adjustMode
    */
    
    @Nullable
    @JsonProperty("adjustMode")
    AdjustMode adjustMode,
/**
    * Get scaling
    */
    
    @Nullable
    @JsonProperty("scaling")
    Boolean scaling

) implements FlexComponent {
/**
     * Gets or Sets style
     */
    public enum Style {
@JsonProperty("primary")
      PRIMARY,
    @JsonProperty("secondary")
      SECONDARY,
    @JsonProperty("link")
      LINK,
    

      @JsonEnumDefaultValue
      UNDEFINED;
    }
/**
     * Gets or Sets gravity
     */
    public enum Gravity {
@JsonProperty("top")
      TOP,
    @JsonProperty("bottom")
      BOTTOM,
    @JsonProperty("center")
      CENTER,
    

      @JsonEnumDefaultValue
      UNDEFINED;
    }
/**
     * Gets or Sets position
     */
    public enum Position {
@JsonProperty("relative")
      RELATIVE,
    @JsonProperty("absolute")
      ABSOLUTE,
    

      @JsonEnumDefaultValue
      UNDEFINED;
    }
/**
     * Gets or Sets height
     */
    public enum Height {
@JsonProperty("md")
      MD,
    @JsonProperty("sm")
      SM,
    

      @JsonEnumDefaultValue
      UNDEFINED;
    }
/**
     * Gets or Sets adjustMode
     */
    public enum AdjustMode {
@JsonProperty("shrink-to-fit")
      SHRINK_TO_FIT,
    

      @JsonEnumDefaultValue
      UNDEFINED;
    }


}
